[build]
rustflags = [
    "-C",
    "link-arg=-nostdlib",
    "-C",
    "link-arg=-static",
    "-C",
    "link-arg=-Wl,-M,-Tshellcode.ld,-subsystem,windows,--build-id=none",
    "-C",
    "relocation-model=pic",
]
